apiVersion: v1
kind: Pod
metadata:
  name: heap2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd_3
  containers:
      - name: heap2
        image: andrewlp/heap_test2:latest
        ports:
          - containerPort: 1883
        command: [ "python", "subber.py"]
