apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    run: connectApi
spec:
    selector:
      matchLabels:
        run: connectApi
    spec:
      containers:
      - name: client
        image: sorter:latest
        ports:
          - containerPort: 3000
    nodeSelector:
      disktype: ssd_3
